### PR TITLE
LPS-60762

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
Hi Dale,

a sturture name has been escaped and saved "within xml type" in the database.
if we escaped one more time in the UI , it will be double escaped.

currently this issue only occurs in WCM AND DM, so not fixed it in "liferay-frontend:add-menu-item"
for safety.


David.

**Comment by daviddotzhang** [comment]
Hi Dale,

I think it will be better if we  can keep the pull request for a while ,as other XSS still exists and LPS is in review.

once all the other LPS merged, then we can continue.

David.

**Comment by daledotshan** [comment]
Hey David,
Could you more clear?   which LPS this pull request depends on

**Comment by daviddotzhang** [comment]
HI Dale,

LPS-60598, there are two alerts, I will cherrypick LPS-60598 and test whether this is still right.

**Pull request closed without merging**
