### PR TITLE
LPS-60870: Categories should persist with respect to file version

### PR DESCRIPTION
**Pull request by mosoni**
Hi Dale,

As of now Assets were created with respect to Dlfileentry, but whenever a draft version created it doesn't store any entry into assetentry and corresponding assetcategory.

With this Logic, asset entry will have entries with respect to version of files and assetcategory will follow the same. Similar logic was already implemented in Knowledgebase therefore to make it consistent, i used similar logic here.

Thanks,
Mohit

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Mohit,
I can not replicate this issue with master Can you double check it again?
Are you choose Categorization or related asset in document library

**Comment by mosoni** [comment]
Hi @daledotshan ,

I am still able to reproduce the issue.
you have to first add the category and click on Document and Media--> Categorization and select category. You can follow the steps mentioned in LPS.

Let me know if you still unable to reproduce .

Thanks,
Mohit

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@daledotshan 

FYI I retested this because the results are stale (almost a month old). QA has an interest in this fix as well. We have a functional test for this specific scenario (LPS-60870) that support asked us to write that has been failing because of the bug.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@mosoni 
Some of the modules integration tests failed on this pull. Those tests typically don't fail, so I think this pull probably caused them.

You can look into them here: https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/51239/#showFailuresLink

**Comment by daledotshan** [comment]
Hey Mohit
this issue should be same with https://github.com/sergiogonzalez/liferay-portal/pull/3209/commits/ffbf93daf977f343b8046c9e0b0c3123f2126ddd

**Pull request closed without merging**
