### PR TITLE
LPS-68580 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @daledotshan @sherlyliu 

I did a bunch of changes in the JSPs but I didn't test them.
Could you please ensure that all the JSPs compile and that they work as expected?

In https://github.com/daledotshan/liferay-portal/pull/525/commits/7c7fe37a9f8c6273a17971d4fb3fcddb1d388ac2 I found some c:when tags without a c:choose tag for example.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by daledotshan** [comment]
ci:retest

**Comment by sherlyliu** [comment]
Hello @sergiogonzalez,
I tested, everything works fine.

Thanks,
Sherly

**Comment by daledotshan** [comment]
closed

**Pull request closed without merging**
