### PR TITLE
[Technical-Support] LPS-69552

### PR DESCRIPTION
**Pull request by yuhai**
The root issue is when select Site, we can see "1 child site" link in parentsite and when click this link, the original logic checks the user whether own parentSite view permission. Because parentsite is visible in UI and the user is member of this parentSite. We should use localserviceImpl instead of service.

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:retest

**Comment by daledotshan** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by daledotshan** [comment]
Pull request submitted to https://github.com/hhuijser/liferay-portal/pull/2761. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by daledotshan** [comment]
Pull request submitted to https://github.com/hhuijser/liferay-portal/pull/2762. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
