### PR TITLE
LPS-59738

### PR DESCRIPTION
**Pull request by bejondshao**

### CODE REVIEW

**Comment by daledotshan** [comment]
see
https://github.com/brianchandotcom/liferay-portal/pull/31712

**Comment by bejondshao** [comment]
Hi Dale,

I'm sorry. This pull request is another part of fix. So it's missed before. We need to commit this too.

**Comment by daledotshan** [comment]
Hey bejond,
After I test this fix, seems it not work as expected. please send your fix.

**Comment by bejondshao** [comment]
Hi Dale,
I'll check it later

**Pull request closed without merging**
