### PR TITLE
LPS-61081

### PR DESCRIPTION
**Pull request by yuhai**
The issue was caused by LPS-55591's the commits "Create taglib for organization search container 
results" and "Use liferay-ui:organization-search-container-results taglib".

For assign orgs, we still search datas from database. If search from index, we never added the logic. So we should keep this.

In addition, when we use useIndexer=true, it means we have search logic from index, please refer to the commits "LPS-55591 Use liferay-ui:organization-search-container-results taglib" other changes.

The fix also refers to the commit "LPS-60611 Do not use indexer when searching members in password policies", this change also was caused by LPS-55591's the commits "Create taglib for user search container results" and "Use liferay-ui:user-search-container-results taglib".

For other parts, for example, edit_role_assignments_users.jsp, we used search from database. After applying LPS-55591 fix, we will firstly search from index. This is ok for this. Because our logic handles index. Please refer to the below logic:

**When assign users to this role.**
RolesAdminPortlet.editRoleAssignments()->UserServiceImpl.addRoleUsers()->UserLocalServiceImpladdRoleUsers() {reindex(userIds);}-> UserIndex.doGetDocument({document.addKeyword("roleIds", user.getRoleIds());})

**When search, the below codes will match the index field so that users can be gotten from index.**
UserIndexer.addContextQueryParams(){else if (key.equals("usersRoles")) {
            contextFilter.addRequiredTerm("roleIds", String.valueOf(value));
        }}

I don't change other parts. If according to the previous logic, we also should change it by setting useIndexer="<%= false %>". Please decide whether we also should change them by referring to the commit "LPS-55591 Use liferay-ui:user-search-container-results taglib".

Thanks,
Hai

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Hai,
I do not think this is proper solution for this issue as you said we might not implement index about usergroup and orgnization, but we implement index for user and site. I also test to assign and unassign a user or site , it works well.

So could you please double check it is bug or just not implementation index? we it is not implementation, can we implement it?

I know password policy use same way with you, but we need to figure out is it possible to implement the index for org and user group? if we can implement it would be perfect.
Thanks,
Dale

**Comment by yuhai** [comment]
Hi Dale,

"but we implement index for user and site. "

We implement index user, I think because other parts also used this function. That is to say, index user logic still existed before LPS-55591. You can refer to the commit "LPS-55591 Use <liferay-ui:user-search-container-results> taglib" changed in view_flat_users.jspf. It can explain index user still existed. But the logic is not used for assign uses to role before LPS-55591. 

After we apply LPS-55591 fix (use <liferay-ui:user-search-container-results> label), due to index user still exist, so this works for user.

It doesn't work for site.  Because assign site to role is from database, not index. Please refer to edit_role_assignments_sites.

Actually, we also can implement the index for password policy if we want to do it. When I worked on LPS-61077. I want to add index for password policy. And found the LPS-60611 solves it by changing search from database(not from index). So it seems we don't want to do that.

As for my suspect, before LPS-55591, even though we have index user logic, but we didn't use it when assign user to roles (the commit "LPS-55591 Use <liferay-ui:user-search-container-results> taglib"). After apply this, whether we should add useIndexer="<%= false %>" to keep the same as the original logic.

Hope it can clarify this.

Thanks,
Hai

**Comment by daledotshan** [comment]
https://github.com/hhuijser/liferay-portal/pull/2565

**Comment by daledotshan** [comment]
https://github.com/hhuijser/liferay-portal/pull/2565

**Pull request closed without merging**
