### PR TITLE
Lps 51444 Some image files can't be read correctly when setting portal.proxy.path

### PR DESCRIPTION
**Pull request by bejondshao**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Bejond,
I just have one concern about this fix, could you test it again with custom portal context name + portal.proxy.path?

**Comment by bejondshao** [comment]
Hi Dale,

This could not test by now. I tried before but failed. It means we can't
access portal through Apache when service context and proxy path are both
changed.

Bejond Shao

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Comment by lipusz** [comment]
Hi Guys,

I've assigned this issue to me and working on it. You can close this one for now.
I'll keep you updated.

Regards,
Tibor

**Comment by lipusz** [comment]
Regarding Dale's concern, I think you just need to set
````conf
ProxyPreserveHost On
ProxyPass /path/ http://localhost:8080/contextname/
ProxyPassReverse /path/ http://localhost:8080/contextname/
````

or

````conf
ProxyPass /path/ http://localhost:8080/contextname/
ProxyPassReverse /path/ http://localhost:8080/contextname/
````

**Comment by lipusz** [comment]
Regarding Dale's concern, I think you just need to set
````conf
ProxyPreserveHost On
ProxyPass /path/ http://localhost:8080/contextname/
ProxyPassReverse /path/ http://localhost:8080/contextname/
````

or

````conf
ProxyPreserveHost On
ProxyPass /path/ ajp://localhost:8080/contextname/
ProxyPassReverse /path/ ajp://localhost:8080/contextname/
````

for Apache2

**Pull request closed without merging**
