### PR TITLE
LPS-61680

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
Hi dale,

Fix reasons:

As we have implemented "AutoEscapeBean" mode. 
-->see class Handler

once the class method.getAnnotation(AutoEscape.class) != null)  it will escape the mode.

"DDLRecordModel" has a method "getUserName" , and the method meets the escape mode just metioned above.  

@AutoEscape
@Override
public String getUserName();

thanks
David.

**Comment by daledotshan** [comment]
Hey David,
Could you explain why you remove the escape in the despictive.jsp file?
After I looked at the source code I found author variable should set from taglib <liferay-ui:app-view-entry, if you remove the code from taglib unless you can make sure all the place call the taglib <liferay-ui:app-view-entry pass a safe author variable.

**Comment by daviddotzhang** [comment]
Hi Dale,

when search "author="<%=", we can find that "folderModel", "ddmDataProviderInstanceModel", "ddlRecordSetModel", "BookmarksEntryModel",  the method  "getUserName" contains "@AutoEscape"

currently it should be safe.

thanks
David.

**Comment by daledotshan** [comment]
reviewed and sent to Hugo
https://github.com/hhuijser/liferay-portal/pull/2588

**Pull request closed without merging**
