### PR TITLE
LPS-67197 Getting portlet preferences from database.

### PR DESCRIPTION
**Pull request by zxdgoal**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey John,
You sent to a wrong branch, it should be ee-7.0.x right

**Comment by zxdgoal** [comment]
We should not fix it in Trunk at first?

**Comment by daledotshan** [comment]
ci:retest

**Comment by daledotshan** [comment]
Hey John,
Seems something wrong with your pull request because github close your pull request automatically
Could you double check it

**Pull request closed without merging**
