### PR TITLE
LPS-61830

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
According to LPS explainations:

Now the fixed behavior is that:

if the thread is a question
    the "flag" column will show:
else:
    the "flag" column will be hide:

**Comment by daledotshan** [comment]
Hey David,
For example if you have two MB trhead one is question and one is not question, your fix will cause the ui information confused.

**Comment by daviddotzhang** [comment]
Thanks.

On Mon, Jan 11, 2016 at 1:22 PM, Dale Shan <notifications@github.com> wrote:

> Hey David,
> For example if you have two MB trhead one is question and one is not
> question, your fix will cause the ui information confused.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daledotshan/liferay-portal/pull/387#issuecomment-170434633>
> .
>



-- 
David

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Comment by daviddotzhang** [comment]
Hi Zsolt,


Thanks a lot for reminding me that this is different from the DXP workflow.

As you have mentioned on the PR,
https://github.com/ZoltanTakacs/liferay-portal-ee/pull/1972

I do not aware how to patch a LCS portlet for a DXP customer. is there any
document I can follow with ?




Thanks,
David.

**Pull request closed without merging**
