### PR TITLE
LPS-65895 Wiki import fails with 'Copy as new' option for the second time

### PR DESCRIPTION
**Pull request by sherlyliu**

### CODE REVIEW

**Comment by sherlyliu** [comment]
Import wiki with "Copy as new", will create a new wiki page, so needn't set uuid in serviceContext. The existingPage should always be null, so needn't fetch it.

**Comment by daledotshan** [comment]
ci:retest

**Comment by daledotshan** [comment]
I have some question here:
1. since this issue happen on when import wiki page on second time, so why following api
wikiPageLocalService.fetchPage(
			nodeId, page.getTitle());
return null,   is it caused by nodeId changed all the time?

2. it should not have two tab space in line 202

3. the code should have a space between line 199 and line 200

4. I guess you did not run ant format-source please remember you need to always run ant format-source  before you send a pull request

5.  the code on 224 there is a extra space

6. the code on 214 there is a extra space

7.  why we only allow update wikipage resouce when strategy is mirror

**Comment by daledotshan** [comment]
reviewed and sent to Hugo
https://github.com/hhuijser/liferay-portal/pull/2653

**Pull request merged**
