### PR TITLE
LPS-57634

### PR DESCRIPTION
**Pull request by bejondshao**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Bejond,
I did  ant build-services base your fix, but I found all of your code get rollback.

I remember we encounter same problem before, so could you please share the solution for me.

Thanks,
Dale

**Comment by bejondshao** [comment]
Hi Dale,

first, go to modules/portal/portal-wab-extender/ run "../../../gradlew deploy"
then go to portal-imple/ run "ant build-services"
then run ant deploy just in case.

**Comment by bejondshao** [comment]
Hi Dale,

I remember I build the module first, then go to portal-impl/ run "ant build-services", related files are changed.

**Comment by bejondshao** [comment]
Hi Dale,

Would you have a look at it?

Thanks

**Comment by daledotshan** [comment]
I got some problem when I did source formatting. I tried several times always some irrelative file be changed.

**Comment by bejondshao** [comment]
If the files are not related with my changing, so we can ignore these changes I think.

**Comment by daledotshan** [comment]
reviewed and sent to Hugo
https://github.com/hhuijser/liferay-portal/pull/2602

**Pull request closed without merging**
