### PR TITLE
LPS-67436

### PR DESCRIPTION
**Pull request by sherlyliu**

### CODE REVIEW

**Comment by sherlyliu** [comment]
LPP ticket: https://issues.liferay.com/browse/LPP-22039
Fix the issue about layout broken in Asset Publisher detail's page for Chinese.

**Comment by daledotshan** [comment]
Hey Sherly,
Your fix is incomplete.
I did a search with string get-url-or-webdav-url=  and I found there is lot of place need to fix.


bin/content/Language_fr_CA.properties:get-url-or-webdav-url=Récupérer <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_el.properties:get-url-or-webdav-url=Λήψη ενός <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_fa.properties:get-url-or-webdav-url=دریافت <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_de.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:;">URL</a> oder <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a> anzeigen.
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_es.properties:get-url-or-webdav-url=Obtenga <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_ro.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_da.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_eu.properties:get-url-or-webdav-url=Lortu <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_tr.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_et.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_cs.properties:get-url-or-webdav-url=Získat <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_hi_IN.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_hr.properties:get-url-or-webdav-url=Dohvati <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_it.properties:get-url-or-webdav-url=Ottieni <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_lt.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_sr_RS_latin.properties:get-url-or-webdav-url=Daj <a class="show-url-file" href="javascript:;">URL</ a> ili <a class="show-webdav-url-file" href="javascript:;">WebDAVURL </>.
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_in.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_nb.properties:get-url-or-webdav-url=Hent <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_ja.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:;">URL</a>か<a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>を取得する
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_zh_TW.properties:get-url-or-webdav-url=取得<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_hu.properties:get-url-or-webdav-url=Lekér <a class="show-url-file" href="javascript:;">URL-t</a> vagy <a class="show-webdav-url-file" href="javascript:;">WebDAV URL-t</a>.
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_uk.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_vi.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_iw.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_fi.properties:get-url-or-webdav-url=Ota <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_gl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_ru.properties:get-url-or-webdav-url=Получить <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_nl_BE.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_en.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_ar.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_pt_PT.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_ko.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_nl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> of <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a> verkrijgen.
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_zh_CN.properties:get-url-or-webdav-url=获取<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_sl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_pl.properties:get-url-or-webdav-url=Pobierz <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_lo.properties:get-url-or-webdav-url=ຮັບ <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_sk.properties:get-url-or-webdav-url=Získajte <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_pt_BR.properties:get-url-or-webdav-url=Obter a <a class="show-url-file" href="javascript:;">URL</a> ou <a class="show-webdav-url-file" href="javascript:;">URL WebDAV</a>.
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_bg.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_sv.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_fr.properties:get-url-or-webdav-url=Récupérer <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_sr_RS.properties:get-url-or-webdav-url=Дај <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/build/unzipped-jar/content/Language_ca.properties:get-url-or-webdav-url=Obtenir una <a class="show-url-file" href="javascript:;">URL</a> o una <a class="show-webdav-url-file" href="javascript:;">URL de WebDAV</a>.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_el.properties:get-url-or-webdav-url=Λήψη ενός <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_fa.properties:get-url-or-webdav-url=دریافت <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_de.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:;">URL</a> oder <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a> anzeigen.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_es.properties:get-url-or-webdav-url=Obtenga <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_ro.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_da.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_eu.properties:get-url-or-webdav-url=Lortu <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_tr.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_et.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_cs.properties:get-url-or-webdav-url=Získat <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_hi_IN.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_hr.properties:get-url-or-webdav-url=Dohvati <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_it.properties:get-url-or-webdav-url=Ottieni <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_lt.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_sr_RS_latin.properties:get-url-or-webdav-url=Daj <a class="show-url-file" href="javascript:;">URL</ a> ili <a class="show-webdav-url-file" href="javascript:;">WebDAVURL </>.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_in.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_nb.properties:get-url-or-webdav-url=Hent <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_ja.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:;">URL</a>か<a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>を取得する
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_zh_TW.properties:get-url-or-webdav-url=取得<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_hu.properties:get-url-or-webdav-url=Lekér <a class="show-url-file" href="javascript:;">URL-t</a> vagy <a class="show-webdav-url-file" href="javascript:;">WebDAV URL-t</a>.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_uk.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_vi.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_iw.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_fi.properties:get-url-or-webdav-url=Ota <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_gl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_ru.properties:get-url-or-webdav-url=Получить <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_nl_BE.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_en.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_ar.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_pt_PT.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_ko.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_nl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> of <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a> verkrijgen.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_zh_CN.properties:get-url-or-webdav-url=获取<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_sl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_pl.properties:get-url-or-webdav-url=Pobierz <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_lo.properties:get-url-or-webdav-url=ຮັບ <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_sk.properties:get-url-or-webdav-url=Získajte <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_pt_BR.properties:get-url-or-webdav-url=Obter a <a class="show-url-file" href="javascript:;">URL</a> ou <a class="show-webdav-url-file" href="javascript:;">URL WebDAV</a>.
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_bg.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_sv.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_fr.properties:get-url-or-webdav-url=Récupérer <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_sr_RS.properties:get-url-or-webdav-url=Дај <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_ca.properties:get-url-or-webdav-url=Obtenir una <a class="show-url-file" href="javascript:;">URL</a> o una <a class="show-webdav-url-file" href="javascript:;">URL de WebDAV</a>.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_el.properties:get-url-or-webdav-url=Λήψη ενός <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_fa.properties:get-url-or-webdav-url=دریافت <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_de.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:;">URL</a> oder <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a> anzeigen.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_es.properties:get-url-or-webdav-url=Obtenga <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_ro.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_da.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_eu.properties:get-url-or-webdav-url=Lortu <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_tr.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_et.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_cs.properties:get-url-or-webdav-url=Získat <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_hi_IN.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_hr.properties:get-url-or-webdav-url=Dohvati <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_it.properties:get-url-or-webdav-url=Ottieni <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_lt.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_sr_RS_latin.properties:get-url-or-webdav-url=Daj <a class="show-url-file" href="javascript:;">URL</ a> ili <a class="show-webdav-url-file" href="javascript:;">WebDAVURL </>.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_in.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_nb.properties:get-url-or-webdav-url=Hent <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_ja.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:;">URL</a>か<a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>を取得する
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_zh_TW.properties:get-url-or-webdav-url=取得<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_hu.properties:get-url-or-webdav-url=Lekér <a class="show-url-file" href="javascript:;">URL-t</a> vagy <a class="show-webdav-url-file" href="javascript:;">WebDAV URL-t</a>.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_uk.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_vi.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>. (Automatic Copy)
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_iw.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_fi.properties:get-url-or-webdav-url=Ota <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_gl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_ru.properties:get-url-or-webdav-url=Получить <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_nl_BE.properties:get-url-or-webdav-url=<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_en.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_ar.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_pt_PT.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_ko.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_nl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> of <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a> verkrijgen.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_zh_CN.properties:get-url-or-webdav-url=获取<a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_sl.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_pl.properties:get-url-or-webdav-url=Pobierz <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_lo.properties:get-url-or-webdav-url=ຮັບ <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:;">URL</a> or <a class="show-webdav-url-file" href="javascript:;">WebDAV URL</a>.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_sk.properties:get-url-or-webdav-url=Získajte <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_pt_BR.properties:get-url-or-webdav-url=Obter a <a class="show-url-file" href="javascript:;">URL</a> ou <a class="show-webdav-url-file" href="javascript:;">URL WebDAV</a>.
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_bg.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_sv.properties:get-url-or-webdav-url=Get <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_fr.properties:get-url-or-webdav-url=Récupérer <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_sr_RS.properties:get-url-or-webdav-url=Дај <a class="show-url-file" href="javascript:
modules/apps/collaboration/document-library/document-library-web/classes/content/Language_ca.properties:get-url-or-webdav-url=Obtenir una <a class="show-url-file" href="javascript:;">URL</a> o una <a class="show-webdav-url-file" href="javascript:;">URL de WebDAV</a>.
portal-impl/src/content/Language_fr_CA.properties:get-url-or-webdav-url=Récupérer <a class="show-url-file" href="javascript:
portal-impl/classes/content/Language_fr_CA.properties:get-url-or-webdav-url=Récupérer <a class="show-url-file" href="javascript:

**Comment by sherlyliu** [comment]
@daledotshan 
In 62x, only Japanese transaction is correct, Chinese isn't right, I translated it by myself.
For the other languages, I don't know how to translate, so I cannot add them.

**Comment by daledotshan** [comment]
fix sent to Hugo for further review
https://github.com/hhuijser/liferay-portal/pull/2692

**Pull request closed without merging**
