### PR TITLE
LPS-53626 Breadcrumb missing in document media display portlet.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Dale

We want to show breadcrumb for current root folder when changing root folder in configuration of DM and DMD. This will make it more user-friendly.

Please help reviewing 

Thanks
John.

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey John,
I am completely sure if the issue is a bug, after I applied your fix, I can see the Breadcrumb only show one folder name, for example you create a folder a and a subfolder b, if you choose b as the root folder of document library we should see the Breadcrumb like a/b right? But actually it just show b

**Comment by zxdgoal** [comment]
Hey Dale. 

After assigning folderID, the breadcrumb will show a/b. 

This looks like improment. 

But for documents display, ignoreRootFolder is missing, this is a bug. Because in document media, we did pass this value as TRUE. 

Without ignoreRootFolder as true, breadcrumb dose not work correctly. 

If you consider passing folderID is not a good decision, you revert it and comment on this pr. 

Thanks
John

**Comment by zxdgoal** [comment]
Hey, Dale.

I just rebased this pr to latest master.

Please re-test.

Thanks
John.

**Comment by daledotshan** [comment]
see
https://github.com/hhuijser/liferay-portal/pull/2296

**Pull request closed without merging**
