### PR TITLE
LPS-57500 BBCode parsing errors occur when using the message boards portlet.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Dale

This is a fix for LPS-57500.

Please help review

Thanks
John.

### CODE REVIEW

**Comment by daledotshan** [comment]
https://github.com/hhuijser/liferay-portal/pull/2436

**Comment by ipeychev** [comment]
Hey @zxdgoal & @hhuijser,

Can we start adding some tests to this parser? When I added it, there was no test infrastructure in Portal at all (neither in Frontend, nor in Backend) and I still regret I added something complex which does not have tests.

We continue to add random fixes here without tests and I'm sure you know where this road goes - we will continue to make changes until the code becomes so buggy, that finally we will admit we have to rewrite it.

At least now we have tests for Backend and I think we should add tests.

Thanks,

**Comment by ipeychev** [comment]
@zxdgoal 

John, I highly respect your efforts and appreciate the, but I just don't want to put this in Portal without tests.
There are too many changes and I don't believe they are not adding some regressions. When I wrote the original code, I did all the changes very carefully, because there were so many different cases to take into consideration.

Now I don't have the context in my mind so how am I supposed to review this? I don't remember anything and there are no any tests to prove there are no regressions.

If this works and the customer is happy - give it to him, but fixes like this I think we shouldn't accept without tests.

I know you have nothing to do with this and it is not your fault we don't have tests. But we should start doing them. Otherwise, this code will become unsupportable.

Thanks,

**Comment by hhuijser** [comment]
Hey @ipeychev 

I completely agree with everything you say (as I always do).
However... giving out fixes to customers that are not my preferred option. Firstly, because as you'll agree, those fixes are not tested, and secondly, the customer upgrades and forgets about the fix, and the bug is back...

I think this would be a good time to create some tests for bbcode, and John is happy to help with this, but since we don't have any yet and this will be something that he doesn't know too much about, would you (or do you know of someone else) be able to help him with this task?

Thanks!

**Comment by ipeychev** [comment]
Hey @hhuijser ,

I asked Sergio and he created everything what we need to do tests for the backend BBCode parser. I just sent @zxdgoal a [PR](https://github.com/zxdgoal/liferay-portal/pull/8).

Let's do as much as possible test there. Meanwhile, I will think how to do tests for the client side parser.

Thanks,

**Pull request closed without merging**
