### PR TITLE
LPS-58669 Journal's content isn't shown in search result's description when its content is searched out.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Dale

Please help review

Thanks
John.

### CODE REVIEW

**Comment by daledotshan** [comment]
I have some question about this fix
1. why we put content into description, is it a real bug?

2. If you change to use content instead of description, how about you search a keyword in description and not exist in content? does it still get the correct search result

Thanks,
Dale

**Comment by zxdgoal** [comment]
Hey Dale

1. This is a regression bug. It was shown content as description. But due to LPS-57292, it shows description now.

2. In this case, the key word in description won't be shown. But this is how it works before LPS-57292.

If we can only show either journal's content or its summary(description). I will vote to show content as it much more likely that a end user wants to search a key from content, rather than summary.

Thanks
John.

**Comment by daledotshan** [comment]
Hey John,
I think we can not tell if it is a regression bug right now, in the beginning we use summary.getContent() show description(but it has a bug) after then we change to show description only, and now you change to show content only (Also it cause  sql query, get content performance is not good than get title).

In my opinion this fix looks not so reasonable. This is more like highlight text design issue please double check with Hugo if he like this fix.

Thanks,
Dale

**Comment by daledotshan** [comment]
sent to Hugo for review
https://github.com/hhuijser/liferay-portal/pull/2466

**Pull request closed without merging**
